version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python app/main.py
    tty: true
    volumes:
      - ./:/backend/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
      DATABASE_URL: "postgresql+asyncpg://myuser:mypassword@postgres:5432/mydatabase"
    depends_on:
      - "postgres"
    ports:
      - "8000:8000"

volumes:
  postgres_data:
