name: capstone
channels:
  - conda-forge
dependencies:
  - fastapi=0.110.*
  - pandas=2.2.*
  - pydantic=2.6.*
  - pydantic-core=2.16.*
  - pydantic-settings=2.2.*
  - python=3.11.*
  - python-dotenv=1.0.*
  - sqlalchemy=2.0.*
  - alembic==1.13.*
  - asyncpg==0.29.*
  - scikit-surprise==1.1.*
  - psycopg==3.1.*