"""Added top_recs table

Revision ID: 8a8215516169
Revises: 14f59d0cffd1
Create Date: 2024-06-12 01:52:36.052897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a8215516169'
down_revision: Union[str, None] = '14f59d0cffd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('top_recs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('prediction', sa.Float(), nullable=False),
    sa.Column('date_predicted', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('fk_top_recs_book_id_book')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_top_recs_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'book_id', name=op.f('pk_top_recs'))
    )
    op.create_index(op.f('ix_top_recs_prediction'), 'top_recs', ['prediction'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_top_recs_prediction'), table_name='top_recs')
    op.drop_table('top_recs')
    # ### end Alembic commands ###
